name: Build
on: [push, pull_request]
jobs:
    unit-tests:
        name: unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.5.0
              with:
                  node-version: 14.16.0
            - name: Install node.js packages
              run: npm install
            - name: Check prettier formatting
              run: npm run prettier:check
            - name: Run generator tests
              run: npm test
